//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NBlackout.MoneyManager.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NBlackout.MoneyManager.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leur affecter une organisme.
        /// </summary>
        public static string Actions_AffectOrganization {
            get {
                return ResourceManager.GetString("Actions_AffectOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choisir.
        /// </summary>
        public static string Actions_Choose {
            get {
                return ResourceManager.GetString("Actions_Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supprimer.
        /// </summary>
        public static string Actions_Delete {
            get {
                return ResourceManager.GetString("Actions_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Désactiver la répétition.
        /// </summary>
        public static string Actions_DisableAutoReschedule {
            get {
                return ResourceManager.GetString("Actions_DisableAutoReschedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier.
        /// </summary>
        public static string Actions_Edit {
            get {
                return ResourceManager.GetString("Actions_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activer la répétion.
        /// </summary>
        public static string Actions_EnableAutoReschedule {
            get {
                return ResourceManager.GetString("Actions_EnableAutoReschedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importer.
        /// </summary>
        public static string Actions_Import {
            get {
                return ResourceManager.GetString("Actions_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replanifier.
        /// </summary>
        public static string Actions_Reschedule {
            get {
                return ResourceManager.GetString("Actions_Reschedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tout replanifier.
        /// </summary>
        public static string Actions_RescheduleAll {
            get {
                return ResourceManager.GetString("Actions_RescheduleAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réenvoyer.
        /// </summary>
        public static string Actions_ReSend {
            get {
                return ResourceManager.GetString("Actions_ReSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enregistrer.
        /// </summary>
        public static string Actions_Save {
            get {
                return ResourceManager.GetString("Actions_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envoyer.
        /// </summary>
        public static string Actions_Send {
            get {
                return ResourceManager.GetString("Actions_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tout afficher.
        /// </summary>
        public static string Actions_ShowAll {
            get {
                return ResourceManager.GetString("Actions_ShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se connecter.
        /// </summary>
        public static string Actions_SignIn {
            get {
                return ResourceManager.GetString("Actions_SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se déconnecter.
        /// </summary>
        public static string Actions_SignOut {
            get {
                return ResourceManager.GetString("Actions_SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valider.
        /// </summary>
        public static string Actions_Validate {
            get {
                return ResourceManager.GetString("Actions_Validate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tout valider.
        /// </summary>
        public static string Actions_ValidateAll {
            get {
                return ResourceManager.GetString("Actions_ValidateAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compte.
        /// </summary>
        public static string Labels_Account {
            get {
                return ResourceManager.GetString("Labels_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activité du compte.
        /// </summary>
        public static string Labels_AccountActivity {
            get {
                return ResourceManager.GetString("Labels_AccountActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories de compte.
        /// </summary>
        public static string Labels_AccountCategories {
            get {
                return ResourceManager.GetString("Labels_AccountCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Détails du compte.
        /// </summary>
        public static string Labels_AccountDetails {
            get {
                return ResourceManager.GetString("Labels_AccountDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestion du compte.
        /// </summary>
        public static string Labels_AccountManagement {
            get {
                return ResourceManager.GetString("Labels_AccountManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comptes.
        /// </summary>
        public static string Labels_Accounts {
            get {
                return ResourceManager.GetString("Labels_Accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Labels_Actions {
            get {
                return ResourceManager.GetString("Labels_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activité.
        /// </summary>
        public static string Labels_Activity {
            get {
                return ResourceManager.GetString("Labels_Activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        public static string Labels_Administration {
            get {
                return ResourceManager.GetString("Labels_Administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Montant.
        /// </summary>
        public static string Labels_Amount {
            get {
                return ResourceManager.GetString("Labels_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-replanification.
        /// </summary>
        public static string Labels_AutoReschedule {
            get {
                return ResourceManager.GetString("Labels_AutoReschedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solde.
        /// </summary>
        public static string Labels_Balance {
            get {
                return ResourceManager.GetString("Labels_Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date de début.
        /// </summary>
        public static string Labels_BeginDate {
            get {
                return ResourceManager.GetString("Labels_BeginDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catégories.
        /// </summary>
        public static string Labels_Categories {
            get {
                return ResourceManager.GetString("Labels_Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catégorie.
        /// </summary>
        public static string Labels_Category {
            get {
                return ResourceManager.GetString("Labels_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Livrets.
        /// </summary>
        public static string Labels_CertificateOfDeposit {
            get {
                return ResourceManager.GetString("Labels_CertificateOfDeposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comptes chèques.
        /// </summary>
        public static string Labels_Checking {
            get {
                return ResourceManager.GetString("Labels_Checking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classification.
        /// </summary>
        public static string Labels_Classification {
            get {
                return ResourceManager.GetString("Labels_Classification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Labels_Code {
            get {
                return ResourceManager.GetString("Labels_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paramétrage.
        /// </summary>
        public static string Labels_Configuration {
            get {
                return ResourceManager.GetString("Labels_Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string Labels_Confirmation {
            get {
                return ResourceManager.GetString("Labels_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connexion.
        /// </summary>
        public static string Labels_Connection {
            get {
                return ResourceManager.GetString("Labels_Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultation.
        /// </summary>
        public static string Labels_Consultation {
            get {
                return ResourceManager.GetString("Labels_Consultation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        public static string Labels_Customer {
            get {
                return ResourceManager.GetString("Labels_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients.
        /// </summary>
        public static string Labels_Customers {
            get {
                return ResourceManager.GetString("Labels_Customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tableau de bord.
        /// </summary>
        public static string Labels_Dashboard {
            get {
                return ResourceManager.GetString("Labels_Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestion des données.
        /// </summary>
        public static string Labels_DataManagement {
            get {
                return ResourceManager.GetString("Labels_DataManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Labels_Date {
            get {
                return ResourceManager.GetString("Labels_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Labels_Description {
            get {
                return ResourceManager.GetString("Labels_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Détails.
        /// </summary>
        public static string Labels_Details {
            get {
                return ResourceManager.GetString("Labels_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durée (ms).
        /// </summary>
        public static string Labels_Duration {
            get {
                return ResourceManager.GetString("Labels_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresse email.
        /// </summary>
        public static string Labels_Email {
            get {
                return ResourceManager.GetString("Labels_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activé.
        /// </summary>
        public static string Labels_Enabled {
            get {
                return ResourceManager.GetString("Labels_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date de fin.
        /// </summary>
        public static string Labels_EndDate {
            get {
                return ResourceManager.GetString("Labels_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solde estimé en fin de mois.
        /// </summary>
        public static string Labels_EstimatedBalanceByEndOfMonth {
            get {
                return ResourceManager.GetString("Labels_EstimatedBalanceByEndOfMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Montant attendu.
        /// </summary>
        public static string Labels_ExpectedAmount {
            get {
                return ResourceManager.GetString("Labels_ExpectedAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date attendue.
        /// </summary>
        public static string Labels_ExpectedDate {
            get {
                return ResourceManager.GetString("Labels_ExpectedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charges.
        /// </summary>
        public static string Labels_Expenditure {
            get {
                return ResourceManager.GetString("Labels_Expenditure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fichier.
        /// </summary>
        public static string Labels_File {
            get {
                return ResourceManager.GetString("Labels_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom du fichier.
        /// </summary>
        public static string Labels_FileName {
            get {
                return ResourceManager.GetString("Labels_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prénom.
        /// </summary>
        public static string Labels_FirstName {
            get {
                return ResourceManager.GetString("Labels_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom complet.
        /// </summary>
        public static string Labels_FullName {
            get {
                return ResourceManager.GetString("Labels_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accueil.
        /// </summary>
        public static string Labels_Home {
            get {
                return ResourceManager.GetString("Labels_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string Labels_Import {
            get {
                return ResourceManager.GetString("Labels_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historique des imports.
        /// </summary>
        public static string Labels_ImportHistories {
            get {
                return ResourceManager.GetString("Labels_ImportHistories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revenus.
        /// </summary>
        public static string Labels_Income {
            get {
                return ResourceManager.GetString("Labels_Income", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intitulé.
        /// </summary>
        public static string Labels_Label {
            get {
                return ResourceManager.GetString("Labels_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom.
        /// </summary>
        public static string Labels_LastName {
            get {
                return ResourceManager.GetString("Labels_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dernière synchronisation.
        /// </summary>
        public static string Labels_LastSynchronization {
            get {
                return ResourceManager.GetString("Labels_LastSynchronization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nouvelle association.
        /// </summary>
        public static string Labels_NewAutomationElement {
            get {
                return ResourceManager.GetString("Labels_NewAutomationElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nouvelle catégorie.
        /// </summary>
        public static string Labels_NewCategory {
            get {
                return ResourceManager.GetString("Labels_NewCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nouveau client.
        /// </summary>
        public static string Labels_NewCustomer {
            get {
                return ResourceManager.GetString("Labels_NewCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nouvel élément.
        /// </summary>
        public static string Labels_NewForecast {
            get {
                return ResourceManager.GetString("Labels_NewForecast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nouvelle occurence.
        /// </summary>
        public static string Labels_NewHit {
            get {
                return ResourceManager.GetString("Labels_NewHit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nouvel organisme.
        /// </summary>
        public static string Labels_NewOrganization {
            get {
                return ResourceManager.GetString("Labels_NewOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non.
        /// </summary>
        public static string Labels_No {
            get {
                return ResourceManager.GetString("Labels_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non régulière.
        /// </summary>
        public static string Labels_NotRegular {
            get {
                return ResourceManager.GetString("Labels_NotRegular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non renseigné.
        /// </summary>
        public static string Labels_NotSpecified {
            get {
                return ResourceManager.GetString("Labels_NotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numéro.
        /// </summary>
        public static string Labels_Number {
            get {
                return ResourceManager.GetString("Labels_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ancien mot de passe.
        /// </summary>
        public static string Labels_OldPassword {
            get {
                return ResourceManager.GetString("Labels_OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisme.
        /// </summary>
        public static string Labels_Organization {
            get {
                return ResourceManager.GetString("Labels_Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organismes.
        /// </summary>
        public static string Labels_Organizations {
            get {
                return ResourceManager.GetString("Labels_Organizations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autre.
        /// </summary>
        public static string Labels_Other {
            get {
                return ResourceManager.GetString("Labels_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autres.
        /// </summary>
        public static string Labels_Others {
            get {
                return ResourceManager.GetString("Labels_Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot de passe.
        /// </summary>
        public static string Labels_Password {
            get {
                return ResourceManager.GetString("Labels_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modèle.
        /// </summary>
        public static string Labels_Pattern {
            get {
                return ResourceManager.GetString("Labels_Pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numéro de téléphone.
        /// </summary>
        public static string Labels_PhoneNumber {
            get {
                return ResourceManager.GetString("Labels_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planification.
        /// </summary>
        public static string Labels_Planning {
            get {
                return ResourceManager.GetString("Labels_Planning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fournisseur.
        /// </summary>
        public static string Labels_Provider {
            get {
                return ResourceManager.GetString("Labels_Provider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Montant réel.
        /// </summary>
        public static string Labels_RealAmount {
            get {
                return ResourceManager.GetString("Labels_RealAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date réelle.
        /// </summary>
        public static string Labels_RealDate {
            get {
                return ResourceManager.GetString("Labels_RealDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Récurrent.
        /// </summary>
        public static string Labels_Recurrent {
            get {
                return ResourceManager.GetString("Labels_Recurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comptes épargnes.
        /// </summary>
        public static string Labels_Saving {
            get {
                return ResourceManager.GetString("Labels_Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recherche.
        /// </summary>
        public static string Labels_Search {
            get {
                return ResourceManager.GetString("Labels_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critères de recherche.
        /// </summary>
        public static string Labels_SearchCriterias {
            get {
                return ResourceManager.GetString("Labels_SearchCriterias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggestions.
        /// </summary>
        public static string Labels_Suggestions {
            get {
                return ResourceManager.GetString("Labels_Suggestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titre.
        /// </summary>
        public static string Labels_Title {
            get {
                return ResourceManager.GetString("Labels_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeton.
        /// </summary>
        public static string Labels_Token {
            get {
                return ResourceManager.GetString("Labels_Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tolérance.
        /// </summary>
        public static string Labels_Tolerance {
            get {
                return ResourceManager.GetString("Labels_Tolerance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Labels_Total {
            get {
                return ResourceManager.GetString("Labels_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transactions planifiées.
        /// </summary>
        public static string Labels_TransactionForecasts {
            get {
                return ResourceManager.GetString("Labels_TransactionForecasts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transactions.
        /// </summary>
        public static string Labels_Transactions {
            get {
                return ResourceManager.GetString("Labels_Transactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Labels_Type {
            get {
                return ResourceManager.GetString("Labels_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilisateur.
        /// </summary>
        public static string Labels_User {
            get {
                return ResourceManager.GetString("Labels_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifiant.
        /// </summary>
        public static string Labels_UserName {
            get {
                return ResourceManager.GetString("Labels_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oui.
        /// </summary>
        public static string Labels_Yes {
            get {
                return ResourceManager.GetString("Labels_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compte requis.
        /// </summary>
        public static string Messages_AccountRequired {
            get {
                return ResourceManager.GetString("Messages_AccountRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choisissez un nouveau category pour les comptes affectés.
        /// </summary>
        public static string Messages_ChooseNewAccountCategory {
            get {
                return ResourceManager.GetString("Messages_ChooseNewAccountCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choisissez un nouveau client pour les comptes affectés.
        /// </summary>
        public static string Messages_ChooseNewCustomer {
            get {
                return ResourceManager.GetString("Messages_ChooseNewCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choisissez un nouvel organisme pour les transactions affectées.
        /// </summary>
        public static string Messages_ChooseNewOrganization {
            get {
                return ResourceManager.GetString("Messages_ChooseNewOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choisissez un nouveau category de transaction pour les organismes affectées.
        /// </summary>
        public static string Messages_ChooseNewOrganizationCategory {
            get {
                return ResourceManager.GetString("Messages_ChooseNewOrganizationCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code invalide.
        /// </summary>
        public static string Messages_CodeInvalid {
            get {
                return ResourceManager.GetString("Messages_CodeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code requis.
        /// </summary>
        public static string Messages_CodeRequired {
            get {
                return ResourceManager.GetString("Messages_CodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation requise.
        /// </summary>
        public static string Messages_ConfirmationRequired {
            get {
                return ResourceManager.GetString("Messages_ConfirmationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez confirmer votre changement d&apos;adresse email en cliquant sur le lien suivant : &lt;a href=&quot;{0}&quot;&gt;Confirmation&lt;/a&gt;.
        /// </summary>
        public static string Messages_ConfirmEmailChange {
            get {
                return ResourceManager.GetString("Messages_ConfirmEmailChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Création effectuée.
        /// </summary>
        public static string Messages_CreationDone {
            get {
                return ResourceManager.GetString("Messages_CreationDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous avez choisi de &lt;strong&gt;supprimer&lt;/strong&gt; un category de compte. Êtes-vous sûr ?.
        /// </summary>
        public static string Messages_DeleteAccountCategory {
            get {
                return ResourceManager.GetString("Messages_DeleteAccountCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous avez choisi de &lt;strong&gt;supprimer&lt;/strong&gt; une association entre un compte et une organisme de transaction. Êtes-vous sûr ?.
        /// </summary>
        public static string Messages_DeleteAutomationElement {
            get {
                return ResourceManager.GetString("Messages_DeleteAutomationElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous avez choisi de &lt;strong&gt;supprimer&lt;/strong&gt; un client. Êtes-vous sûr ?.
        /// </summary>
        public static string Messages_DeleteCustomer {
            get {
                return ResourceManager.GetString("Messages_DeleteCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous avez choisi de &lt;strong&gt;supprimer&lt;/strong&gt; un élément de planification. Êtes-vous sûr ?.
        /// </summary>
        public static string Messages_DeleteForecast {
            get {
                return ResourceManager.GetString("Messages_DeleteForecast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous avez choisi de &lt;strong&gt;supprimer&lt;/strong&gt; une occurence de transaction planifiée. Êtes-vous sûr ?.
        /// </summary>
        public static string Messages_DeleteHit {
            get {
                return ResourceManager.GetString("Messages_DeleteHit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous avez choisi de &lt;strong&gt;supprimer&lt;/strong&gt; une organisme de transaction. Si vous la supprimez, chaque transaction qui la référence doit être &lt;strong&gt;réassignée&lt;/strong&gt;..
        /// </summary>
        public static string Messages_DeleteOrganization {
            get {
                return ResourceManager.GetString("Messages_DeleteOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous avez choisi de &lt;strong&gt;supprimer&lt;/strong&gt; un category de transaction. Si vous le supprimez, chaque organisme de transaction qui le référence doit être &lt;strong&gt;réassignée&lt;/strong&gt;..
        /// </summary>
        public static string Messages_DeleteOrganizationCategory {
            get {
                return ResourceManager.GetString("Messages_DeleteOrganizationCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppression effectuée.
        /// </summary>
        public static string Messages_DeletionDone {
            get {
                return ResourceManager.GetString("Messages_DeletionDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation de votre changement d&apos;adresse email.
        /// </summary>
        public static string Messages_EmailChangeConfirmation {
            get {
                return ResourceManager.GetString("Messages_EmailChangeConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresse email au format incorrect.
        /// </summary>
        public static string Messages_EmailInvalid {
            get {
                return ResourceManager.GetString("Messages_EmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La nouvelle adresse email et sa confirmation ne correspondent pas.
        /// </summary>
        public static string Messages_EmailNotMatchingConfirmation {
            get {
                return ResourceManager.GetString("Messages_EmailNotMatchingConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresse email requise.
        /// </summary>
        public static string Messages_EmailRequired {
            get {
                return ResourceManager.GetString("Messages_EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prénom requis.
        /// </summary>
        public static string Messages_FirstNameRequired {
            get {
                return ResourceManager.GetString("Messages_FirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;intitulé doit être composé d&apos;au moins 3 caractères.
        /// </summary>
        public static string Messages_LabelLength {
            get {
                return ResourceManager.GetString("Messages_LabelLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intitulé requis.
        /// </summary>
        public static string Messages_LabelRequired {
            get {
                return ResourceManager.GetString("Messages_LabelRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom requis.
        /// </summary>
        public static string Messages_LastNameRequired {
            get {
                return ResourceManager.GetString("Messages_LastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modification effectuée.
        /// </summary>
        public static string Messages_ModificationDone {
            get {
                return ResourceManager.GetString("Messages_ModificationDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifications effectuées.
        /// </summary>
        public static string Messages_ModificationsDone {
            get {
                return ResourceManager.GetString("Messages_ModificationsDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circulez, il n&apos;y a rien à voir (littéralement) ! Il est grand temps de corriger ça :.
        /// </summary>
        public static string Messages_MoveAlong {
            get {
                return ResourceManager.GetString("Messages_MoveAlong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucune donnée trouvée.
        /// </summary>
        public static string Messages_NoDataFound {
            get {
                return ResourceManager.GetString("Messages_NoDataFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numéro requis.
        /// </summary>
        public static string Messages_NumberRequired {
            get {
                return ResourceManager.GetString("Messages_NumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ancien mot de passe requis.
        /// </summary>
        public static string Messages_OldPasswordRequired {
            get {
                return ResourceManager.GetString("Messages_OldPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisme ou intitulé requis.
        /// </summary>
        public static string Messages_OrganizationOrLabelRequired {
            get {
                return ResourceManager.GetString("Messages_OrganizationOrLabelRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisme requise.
        /// </summary>
        public static string Messages_OrganizationRequired {
            get {
                return ResourceManager.GetString("Messages_OrganizationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le nouveau mot de passe et sa confirmation ne correspondent pas.
        /// </summary>
        public static string Messages_PasswordNotMatchingConfirmation {
            get {
                return ResourceManager.GetString("Messages_PasswordNotMatchingConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot de passe requis.
        /// </summary>
        public static string Messages_PasswordRequired {
            get {
                return ResourceManager.GetString("Messages_PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numéro de téléphone au format incorrect.
        /// </summary>
        public static string Messages_PhoneNumberInvalid {
            get {
                return ResourceManager.GetString("Messages_PhoneNumberInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le nouveau numéro de téléphone et sa confirmation ne correspondent pas.
        /// </summary>
        public static string Messages_PhoneNumberNotMatchingConfirmation {
            get {
                return ResourceManager.GetString("Messages_PhoneNumberNotMatchingConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numéro de téléphone requis.
        /// </summary>
        public static string Messages_PhoneNumberRequired {
            get {
                return ResourceManager.GetString("Messages_PhoneNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fournisseur requis.
        /// </summary>
        public static string Messages_ProviderRequired {
            get {
                return ResourceManager.GetString("Messages_ProviderRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fournisseur indisponible.
        /// </summary>
        public static string Messages_ProviderUnavailable {
            get {
                return ResourceManager.GetString("Messages_ProviderUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre code de securité est : {0}.
        /// </summary>
        public static string Messages_SecurityCode {
            get {
                return ResourceManager.GetString("Messages_SecurityCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending two-factor code using {0} to {1}.
        /// </summary>
        public static string Messages_SendingTwoFactorCode {
            get {
                return ResourceManager.GetString("Messages_SendingTwoFactorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categorie source requise.
        /// </summary>
        public static string Messages_SourceCategoryRequired {
            get {
                return ResourceManager.GetString("Messages_SourceCategoryRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client source requis.
        /// </summary>
        public static string Messages_SourceCustomerRequired {
            get {
                return ResourceManager.GetString("Messages_SourceCustomerRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisme source requise.
        /// </summary>
        public static string Messages_SourceOrganizationRequired {
            get {
                return ResourceManager.GetString("Messages_SourceOrganizationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categorie cible requise.
        /// </summary>
        public static string Messages_TargetCategoryRequired {
            get {
                return ResourceManager.GetString("Messages_TargetCategoryRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titre requis.
        /// </summary>
        public static string Messages_TitleRequired {
            get {
                return ResourceManager.GetString("Messages_TitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeton invalide.
        /// </summary>
        public static string Messages_TokenInvalid {
            get {
                return ResourceManager.GetString("Messages_TokenInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeton requis.
        /// </summary>
        public static string Messages_TokenRequired {
            get {
                return ResourceManager.GetString("Messages_TokenRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to transaction(s) insérée(s).
        /// </summary>
        public static string Messages_TransactionInserted {
            get {
                return ResourceManager.GetString("Messages_TransactionInserted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type requis.
        /// </summary>
        public static string Messages_TypeRequired {
            get {
                return ResourceManager.GetString("Messages_TypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifiant ou mot de passe incorrect.
        /// </summary>
        public static string Messages_UserNameOrPasswordInvalid {
            get {
                return ResourceManager.GetString("Messages_UserNameOrPasswordInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifiant requis.
        /// </summary>
        public static string Messages_UserNameRequired {
            get {
                return ResourceManager.GetString("Messages_UserNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilisateur requis.
        /// </summary>
        public static string Messages_UserRequired {
            get {
                return ResourceManager.GetString("Messages_UserRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} requires TFA verification.
        /// </summary>
        public static string Messages_UserRequiresTfaVerification {
            get {
                return ResourceManager.GetString("Messages_UserRequiresTfaVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppression de la catégorie de compte.
        /// </summary>
        public static string Titles_AccountCategoryDeletion {
            get {
                return ResourceManager.GetString("Titles_AccountCategoryDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Édition de la catégorie de compte.
        /// </summary>
        public static string Titles_AccountCategoryEdition {
            get {
                return ResourceManager.GetString("Titles_AccountCategoryEdition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Édition d&apos;un compte.
        /// </summary>
        public static string Titles_AccountEdition {
            get {
                return ResourceManager.GetString("Titles_AccountEdition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppression de l&apos;association entre le compte et l&apos;organisme de transaction.
        /// </summary>
        public static string Titles_AutomationElementDeletion {
            get {
                return ResourceManager.GetString("Titles_AutomationElementDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Édition de l&apos;association entre un compte et une organisme de transaction.
        /// </summary>
        public static string Titles_AutomationElementEdition {
            get {
                return ResourceManager.GetString("Titles_AutomationElementEdition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppression du client.
        /// </summary>
        public static string Titles_CustomerDeletion {
            get {
                return ResourceManager.GetString("Titles_CustomerDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Édition du client.
        /// </summary>
        public static string Titles_CustomerEdition {
            get {
                return ResourceManager.GetString("Titles_CustomerEdition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Édition de l&apos;adresse email.
        /// </summary>
        public static string Titles_EmailEdition {
            get {
                return ResourceManager.GetString("Titles_EmailEdition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppression de l&apos;élément de planification.
        /// </summary>
        public static string Titles_ForecastDeletion {
            get {
                return ResourceManager.GetString("Titles_ForecastDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Édition de l&apos;élément de planification.
        /// </summary>
        public static string Titles_ForecastEdition {
            get {
                return ResourceManager.GetString("Titles_ForecastEdition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppression de l&apos;occrurence de transaction planifiée.
        /// </summary>
        public static string Titles_HitDeletion {
            get {
                return ResourceManager.GetString("Titles_HitDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Édition de l&apos;occurence de transaction planifiée.
        /// </summary>
        public static string Titles_HitEdition {
            get {
                return ResourceManager.GetString("Titles_HitEdition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Money Manager.
        /// </summary>
        public static string Titles_MoneyManager {
            get {
                return ResourceManager.GetString("Titles_MoneyManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppression de la catégorie d&apos;organisme.
        /// </summary>
        public static string Titles_OrganizationCategoryDeletion {
            get {
                return ResourceManager.GetString("Titles_OrganizationCategoryDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Édition de la catégorie d&apos;organisme.
        /// </summary>
        public static string Titles_OrganizationCategoryEdition {
            get {
                return ResourceManager.GetString("Titles_OrganizationCategoryEdition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppression de l&apos;organisme.
        /// </summary>
        public static string Titles_OrganizationDeletion {
            get {
                return ResourceManager.GetString("Titles_OrganizationDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Édition de l&apos;organisme.
        /// </summary>
        public static string Titles_OrganizationEdition {
            get {
                return ResourceManager.GetString("Titles_OrganizationEdition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Édition du mot de passe.
        /// </summary>
        public static string Titles_PasswordEdition {
            get {
                return ResourceManager.GetString("Titles_PasswordEdition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Édition du numéro de téléphone.
        /// </summary>
        public static string Titles_PhoneNumberEdition {
            get {
                return ResourceManager.GetString("Titles_PhoneNumberEdition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Édition d&apos;une transaction.
        /// </summary>
        public static string Titles_TransactionEdition {
            get {
                return ResourceManager.GetString("Titles_TransactionEdition", resourceCulture);
            }
        }
    }
}
