// <auto-generated />
namespace NBlackout.MoneyManager.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AccountFilter : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AccountFilter));
        
        string IMigrationMetadata.Id
        {
            get { return "201806230757126_AccountFilter"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
