// <auto-generated />
namespace NBlackout.MoneyManager.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class UserCustomerAssociation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserCustomerAssociation));
        
        string IMigrationMetadata.Id
        {
            get { return "201805031415018_UserCustomerAssociation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
